---
title: "Community_data_processing"
author: "Joshua G. Smith"
date: '2022-06-16'
output: html_document
---



#clear workspace and load packages
```{r}

rm(list = ls())

require(dplyr)
require(stringr)
require(tidyr)
require(janitor)
require(vegan)
```


#load environmental data
```{r}

#load data and get mpa-year level means
envr_dat <- readRDS("/home/shares/ca-mpa/data/sync-data/environmental/processed/envr_anomalies_at_mpas.Rds") %>%
            group_by(group, mpa_name, mpa_class, mpa_designation, mpa_defacto_class, mpa_defacto_designation,
                     region3, region4, year)%>%
            dplyr::summarise(across(c("sst_annual_baseline", "sst_monthly_baseline", "sst_annual_obs", "sst_monthly_obs", "sst_monthly_anom",       
            "cuti_annual_baseline", "cuti_monthly_baseline", "cuti_annual_obs", "cuti_monthly_obs", "cuti_monthly_anom",     
            "beuti_annual_baseline", "beuti_monthly_baseline", "beuti_annual_obs", "beuti_monthly_obs", "beuti_monthly_anom",     
              "annual_MOCI"), ~ mean(.x, na.rm = TRUE)))

rocky_envr_vars <- readRDS("/home/shares/ca-mpa/data/sync-data/environmental/processed/envr_anomalies_at_intertidal_mpas.Rds")

```

**Step 1 - process ecological data in species counts / year format**


#Process CCFRP data
```{r}
# ccfrp -------------------------------------------------------------------

#load species level mean fish CPUE
data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/monitoring_ccfrp/CCFRP_derived_data_tables_DataONE"
input_file <- "CCFRP_derived_effort_table.csv" 
CPUE_raw <- read.csv(file.path(data_path, input_file))

#reshape and clean up
CCFRP_CPUE <- CPUE_raw %>%
  mutate(affiliated_mpa = paste(Area,"smr"), #all ccfrp MPAs are defacto SMRs per PI
         mpa_designation = ifelse(MPA_Status == "MPA","smr", MPA_Status))
  
CCFRP_CPUE$mpa_designation <- tolower(CCFRP_CPUE$mpa_designation)
CCFRP_CPUE$mpa_designation <- tolower(CCFRP_CPUE$mpa_designation)

CCFRP_CPUE <- CCFRP_CPUE %>%
                  dplyr::select(year=Year, affiliated_mpa, mpa_designation, Grid_Cell_ID, Common_Name, CPUE_catch_per_angler_hour)%>%
                  mutate(mpa_class="smr", 
                         group="ccfrp") %>%
                  group_by(group, year, affiliated_mpa, mpa_class, mpa_designation, Grid_Cell_ID, Common_Name)%>%
                  dplyr::summarize(CPUE_mean = mean(CPUE_catch_per_angler_hour))%>%  #some species in the raw data have duplicate entries.
                  ungroup() %>%
                  tidyr::pivot_wider(names_from = Common_Name, 
                                     values_from = CPUE_mean) %>%
                  janitor::clean_names()
              
CCFRP_CPUE$affiliated_mpa <- tolower(CCFRP_CPUE$affiliated_mpa)

CCFRP_CPUE$affiliated_mpa <- recode_factor(CCFRP_CPUE$affiliated_mpa, "southeast farallon islands smr" = "southeast farallon island smr") #clean up names

CCFRP_CPUE$affiliated_mpa <- recode_factor(CCFRP_CPUE$affiliated_mpa, "swamis smr" = "swami's smca") #clean up names 


#drop species and combine to higher taxa
#### see reference taxonomy table https://docs.google.com/spreadsheets/d/1vxy0XVOrlNhXD-i9tWL_F9G5h8S3S4OV/edit#gid=2031917236

CCFRP_combined <- CCFRP_CPUE %>%
                  #merge species
                  mutate(blue_rockfish_merge = rowSums(select(.,'blue_rockfish','deacon_rockfish')),
                         mackerel_family_merge = rowSums(select(., 'mackerel_family_scombridae','pacific_chub_mackerel','jack_mackerel')),
                         sanddabs_merge = rowSums(select(., 'pacific_sanddab','sanddab_spp','speckled_sanddab')))%>%
                  select(!(c('blue_rockfish','deacon_rockfish','mackerel_family_scombridae','pacific_chub_mackerel',
                             'pacific_sanddab','sanddab_spp','speckled_sanddab','jack_mackerel'))) %>%
                  #drop species
                  select(!(c('northern_anchovy',
                             'olive_or_yellowtail_rockfish',
                             'pacific_sardine',
                             'petrale_sole',
                             'pile_perch',
                             'rubberlip_seaperch',
                             'sand_sole',
                             'spiny_dogfish',
                             'senorita',
                             'starry_skate',
                             'tubesnout',
                             'silversides_family_atherinopsidae',
                             'un_id_blue_rockfish',
                             'unknown',
                             'unknown_rockfish',
                             'wolf_eel',
                             'yelloweye_rockfish',
                             'bull_sculpin',
                             'pacific_barracuda',
                             'total')))%>%
                  #drop string
                  rename(blue_rockfish = blue_rockfish_merge,
                         mackerel_family = mackerel_family_merge,
                         sanddabs = sanddabs_merge)


#add regions
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
four_region <- readxl::read_excel(file.path(data_path, input_file), sheet=1, skip = 0, na="NA")

regions <- four_region %>%
  dplyr::select(name, region3=bioregion, region4 = four_region_north_ci)

CCFRP_CPUE <- left_join(CCFRP_combined, regions, by=c("affiliated_mpa"="name"))

#clean up a

CCFRP_CPUE <- CCFRP_CPUE %>%
  mutate(MHW = ifelse(year>=2014 & year<=2016, "during",ifelse(year<2014, "before","after")))%>%
  dplyr::select(year, group, region3, region4, MHW, everything())

#drop species that were never observed on the central coast
CCFRP_zero_drop <- CCFRP_CPUE %>% filter(region3=='central') %>%
                    select(!(where(~ any(. != 0))))

CCFRP_cen <- CCFRP_CPUE %>% filter(region3=='central') %>%
                    select(where(~ any(. != 0)))

#Export
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/processed_data/ecological_community_data" 
#write.csv(CCFRP_CPUE,file.path(path_aurora, "CCFRP_species_counts.csv"), row.names = FALSE)

CCFRP_mpa_year_step1 <- CCFRP_cen %>%
                  pivot_longer(cols=10:46, names_to="species",values_to="CPUE")%>%
                  group_by(year, group, region3, region4, MHW, affiliated_mpa, mpa_class, mpa_designation, species)%>%
                  dplyr::summarize(mean_CPUE = mean(CPUE))%>%
                  ungroup()%>%
                  pivot_wider(names_from = "species", values_from = "mean_CPUE")

CCFRP_mpa_year <- left_join(CCFRP_mpa_year_step1, envr_dat, by=c("year","group",
                                                       "region3","region4",
                                                       "mpa_class"="mpa_defacto_class",
                                                       "mpa_designation"="mpa_defacto_designation",
                                                       "affiliated_mpa"="mpa_name"))%>%
                  #filter(!(affiliated_mpa=="trinidad smr"))%>% #not a real MPA per PI
                  dplyr::select(!(c("mpa_class.y","mpa_designation.y")))%>%
                  dplyr::select(1:8,46:61,9:45)

#Export
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/community_climate_derived_data" 
#write.csv(CCFRP_mpa_year,file.path(path_aurora, "CCFRP_mpa_year.csv"), row.names = FALSE)
```





#Process kelp forest fish data

```{r}

data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/monitoring_kelp"
input_file <- "MLPA_kelpforest_fish.4.csv" 
kelp_fish_counts <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names()

#select vars and clean
kelp_fish_counts <- kelp_fish_counts %>%
                    dplyr::select(year, site, zone, level, transect, classcode, count)%>%
                    group_by(year, site, zone, level, transect, classcode)%>%
                    dplyr::summarize(total_count = sum(count)) #counts in raw data are grouped by size class. Take summary across all sizes

#join species names by class code 
input_file <- "MLPA_kelpforest_taxon_table.4.csv"  
kelp_taxon <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names() %>%
                    dplyr::select(classcode, species_definition) %>%
                    distinct() #remove duplicates

kelp_fish_counts<-  left_join(kelp_fish_counts, kelp_taxon, by="classcode")

kelp_fish_counts <- kelp_fish_counts %>%
                    dplyr::select(year, site, zone, level, transect, species=species_definition, total_count)%>%
                    filter(!(species=='Sebastes atrovirens/carnatus/chrysomelas/caurinus'))


#add affiliated_mpa

input_file <- "MLPA_kelpforest_site_table.4.csv" 
kelp_sites <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names() %>%
                    dplyr::select(site, ca_mpa_name_short, mpa_class=site_designation, mpa_designation=site_status)%>%
                    distinct() #remove duplicates

kelp_fish_counts <- left_join(kelp_fish_counts, kelp_sites, by="site")

kelp_fish_counts <- kelp_fish_counts %>%
                    ungroup() %>%
                    dplyr::select(year, affiliated_mpa=ca_mpa_name_short,mpa_class, mpa_designation, zone, level, transect, species,
                                  total_count) %>%
                    mutate(mpa_designation = ifelse(mpa_designation=="reference","ref",mpa_class))


#add 4 regions
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
four_region <- readxl::read_excel(file.path(data_path, input_file), sheet=1, skip = 0, na="NA")

regions <- four_region %>%
  dplyr::select(name, region3=bioregion, region4 = four_region_north_ci)

kelp_fish_counts$affiliated_mpa <- tolower(kelp_fish_counts$affiliated_mpa)

kelp_fish_counts <- left_join(kelp_fish_counts, regions, by=c("affiliated_mpa"="name"))


#add defacto SMRs
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
defacto_smr <- readxl::read_excel(file.path(data_path, input_file), sheet=5, skip = 0, na="NA")%>%
               filter(group=="kelp") %>%
               dplyr::select(affiliated_mpa, mpa_class)
              

kelp_fish_counts <- left_join(kelp_fish_counts, defacto_smr, by="affiliated_mpa")


#clean up
kelp_fish_counts <- kelp_fish_counts %>%
                    mutate(mpa_defacto_designation = ifelse(mpa_designation=="ref","ref",mpa_class.y))%>%
                    dplyr::select(year, region3, region4, affiliated_mpa, mpa_defacto_class = mpa_class.y, mpa_defacto_designation, zone, level, transect, species, total_count)
                 
kelp_fish_counts$mpa_defacto_class <- tolower(kelp_fish_counts$mpa_defacto_class)
kelp_fish_counts$mpa_defacto_designation <- tolower(kelp_fish_counts$mpa_defacto_designation)

kelp_fish_counts <- kelp_fish_counts %>%
                    group_by(year, region3, region4, affiliated_mpa, mpa_defacto_class, mpa_defacto_designation, zone, level, transect, species) %>%
                    dplyr::summarise(counts = sum(total_count)) #make sure species are not duplicates by summarizing at the transect level (total counts)




#reshape to wide format
kelp_fish_counts1 <- kelp_fish_counts %>%
                    pivot_wider(names_from=species, values_from=counts, values_fill = 0) %>%
                    janitor::clean_names()%>%
                    drop_na(region4)%>%
                    mutate(MHW = ifelse(year>=2014 & year<=2016, "during",ifelse(year<2014, "before","after")))%>%
                    dplyr::select(year, region3, region4, affiliated_mpa, mpa_defacto_class, mpa_defacto_designation, MHW, zone, level, transect, everything(),-c(no_organisms_present_in_this_sample))


#drop species and combine to higher taxa
#### see reference taxonomy table https://docs.google.com/spreadsheets/d/1vxy0XVOrlNhXD-i9tWL_F9G5h8S3S4OV/edit#gid=2031917236

kelp_fish_combined <- as.data.frame(kelp_fish_counts1) %>%
                  
                  #merge species
                  dplyr::mutate(citharichthys_merge = rowSums(select(.,'citharichthys','citharichthys_sordidus','citharichthys_stigmaeus')
                                                              ))%>%
                  select(!(c('citharichthys','citharichthys_sordidus','citharichthys_stigmaeus'))) %>%
                  #drop species
                  select(!(c('anisotremus_davidsonii',
                             'cheilotrema_saturnum',
                             'unidentified_fish',
                             'apodichthys_flavidus',
                             'atherinopsidae',
                             'aulorhynchus_flavidus',
                             'bothidae',
                             'clupeiformes',
                             'cryptacanthodes_giganteus',
                             'embiotocidae',
                             'engraulis_mordax',
                             'gobiesox_maeandricus',
                             'hyperprosopon_anale',
                             'hyperprosopon_argenteum',
                             'hyperprosopon_ellipticum',
                             'leiocottus_hirundo',
                             'lethops_connectens',
                             'neoclinus_blanchardi',
                             'pholidae',
                             'pleuronectidae',
                             'rathbunella_alleni',
                             'rathbunella_hypoplecta',
                             'ronquilus_jordani',
                             'sardinops_sagax',
                             'sebastes',
                             'stichaeidae',
                             'syngnathus',
                             'trachurus_symmetricus',
                             'ulvicola_sanctaerosae')))%>%
                  #drop string
                  rename(citharichthys=citharichthys_merge)
                         

#Export
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/processed_data/ecological_community_data" 
#write.csv(kelp_fish_counts,file.path(path_aurora, "kelp_fish_counts.csv"), row.names = FALSE)


kelp_fish_mpa_year_step1 <- kelp_fish_combined %>% 
                  pivot_longer(cols=11:121, names_to="species",values_to="counts")%>%
                  group_by(year, region3, region4, affiliated_mpa, mpa_defacto_class, mpa_defacto_designation, MHW, species)%>%
                  dplyr::summarize(total_counts = sum(counts))%>%
                  ungroup()%>%
                  pivot_wider(names_from = "species", values_from = "total_counts") %>%
                  mutate(group = "kelp")

kelp_fish_mpa_year <- left_join(kelp_fish_mpa_year_step1, envr_dat, by=c("year","group",
                                                       "region3","region4",
                                                       "mpa_defacto_class",
                                                       "mpa_defacto_designation",
                                                       "affiliated_mpa"="mpa_name"))%>%
                  dplyr::select(1:7,119:137,8:118) %>%
                  dplyr::select(!c("mpa_class","mpa_designation")) %>%
                  mutate(group="kelp_fish") %>%
                  dplyr::select(group, everything()) 


#Export year                     
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/ecological_community_data/year_level_with_envr_vars" 
#write.csv(kelp_fish_mpa_year,file.path(path_aurora, "kelp_fish_mpa_year.csv"), row.names = FALSE)
```




#Process kelp swath data
```{r}
data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/monitoring_kelp"
input_file <- "MLPA_kelpforest_swath.4.csv" 
kelp_swath_counts <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names()


#select vars and clean
kelp_swath_counts <- kelp_swath_counts %>%
                    dplyr::select(year, site, zone, transect, classcode, count)%>%
                    group_by(year, site, zone, transect, classcode)%>%
                    dplyr::summarize(total_count = sum(count)) #counts in raw data are grouped by size class. Take summary across all sizes

#join species names by class code 
input_file <- "MLPA_kelpforest_taxon_table.4.csv"  
kelp_taxon <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names() %>%
                    dplyr::select(classcode, species_definition) %>%
                    distinct() #remove duplicates

kelp_swath_counts<-  left_join(kelp_swath_counts, kelp_taxon, by="classcode")

kelp_swath_counts <- kelp_swath_counts %>%
                    dplyr::select(year, site, zone, transect, species=species_definition, total_count)


#add affiliated_mpa

input_file <- "MLPA_kelpforest_site_table.4.csv" 
kelp_sites <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names() %>%
                    dplyr::select(site, ca_mpa_name_short, mpa_class=site_designation, mpa_designation=site_status)%>%
                    distinct() #remove duplicates

kelp_swath_counts <- left_join(kelp_swath_counts, kelp_sites, by="site")

kelp_swath_counts <- kelp_swath_counts %>%
                    ungroup() %>%
                    dplyr::select(year, affiliated_mpa=ca_mpa_name_short,mpa_class, mpa_designation, zone, transect, species, total_count) %>%
                    mutate(mpa_designation = ifelse(mpa_designation=="reference","ref",mpa_class))

#add 4 regions
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
four_region <- readxl::read_excel(file.path(data_path, input_file), sheet=1, skip = 0, na="NA")

regions <- four_region %>%
  dplyr::select(name, region3=bioregion, region4 = four_region_north_ci)

kelp_swath_counts$affiliated_mpa <- tolower(kelp_swath_counts$affiliated_mpa)

kelp_swath_counts <- left_join(kelp_swath_counts, regions, by=c("affiliated_mpa"="name"))



#add defacto SMRs
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
defacto_smr <- readxl::read_excel(file.path(data_path, input_file), sheet=5, skip = 0, na="NA")%>%
               filter(group=="kelp") %>%
               dplyr::select(affiliated_mpa, mpa_class)
              

kelp_swath_counts <- left_join(kelp_swath_counts, defacto_smr, by="affiliated_mpa")


#clean up
kelp_swath_counts <- kelp_swath_counts %>%
                    mutate(mpa_defacto_designation = ifelse(mpa_designation=="ref","ref",mpa_class.y))%>%
                    dplyr::select(year, region3, region4, affiliated_mpa, mpa_defacto_class = mpa_class.y, mpa_defacto_designation, zone, transect, species, total_count)
                 
kelp_swath_counts$mpa_defacto_class <- tolower(kelp_swath_counts$mpa_defacto_class)
kelp_swath_counts$mpa_defacto_designation <- tolower(kelp_swath_counts$mpa_defacto_designation)

kelp_swath_counts <- kelp_swath_counts %>%
                    group_by(year, region3, region4, affiliated_mpa, mpa_defacto_class, mpa_defacto_designation, zone, transect, species) %>%
                    dplyr::summarize(counts = sum(total_count)) #make sure species are not duplicates by summarizing at the transect level (total counts)


#Run this code to aggregate at MPA-year level
#kelp_swath_mpa_year <- kelp_swath_counts %>%
#                    group_by(year, region3, region4, affiliated_mpa, mpa_defacto_class, mpa_defacto_designation, species) %>%
#                    dplyr::summarize(counts = sum(counts)) 


#reshape to wide format
kelp_swath_counts1 <- kelp_swath_counts %>%
                    pivot_wider(names_from=species, values_from=counts, values_fill = 0) %>%
                    janitor::clean_names()%>%
                    drop_na(region4) %>%
                    mutate(MHW = ifelse(year>=2014 & year<=2016, "during",ifelse(year<2014, "before","after")))%>%
                    dplyr::select(year, region3, region4, affiliated_mpa, mpa_defacto_class, MHW, everything())
                    #dplyr::select(-c(no_organisms_present_in_this_sample))



#drop species and combine to higher taxa
#### see reference taxonomy table https://docs.google.com/spreadsheets/d/1vxy0XVOrlNhXD-i9tWL_F9G5h8S3S4OV/edit#gid=2031917236

kelp_swath_counts2 <- as.data.frame(kelp_swath_counts1) %>%
                  
                  #merge species
                  dplyr::mutate(urticina_merge = rowSums(select(.,'urticina', 
                                                          'urticina_coriacea', 'urticina_crassicornis', 'urticina_piscivora')
                                                              ))%>%
                  select(!(c('urticina', 
                                                          'urticina_coriacea', 'urticina_crassicornis', 'urticina_piscivora'))) %>%
                  #drop species
                  select(!(c('anthopleura',
                             'asteroidea',
                             'haliotis',
                             'laminaria',
                             'laminariales',
                             'octopus',
                             'pisaster',
                             'pugettia_spp',
                             'stylasterias_forreri',
                             'urticina_columbiana',
                             'urticina_columbiana_mcpeaki',
                             )))%>%
                  #drop string
                  rename(urticina=urticina_merge)


#drop species that were never observed on the central coast
kelp_swath_zero_drop <- kelp_swath_counts2 %>% filter(region3=='central') %>%
                    select(!(where(~ any(. != 0))))

kelp_swath_counts3 <- kelp_swath_counts2 %>% filter(region3=='central') %>%
                    select(where(~ any(. != 0)))

#Export
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/processed_data/ecological_community_data" 
#write.csv(kelp_swath_mpa_year, file.path(path_aurora, "kelp_swath_mpa_year_counts.csv"), row.names = FALSE)

kelp_swath_mpa_year_step1 <- kelp_swath_counts3 %>%
                        pivot_longer(cols=10:73, names_to="species",values_to="counts")%>%
                        group_by(year, region3, region4, affiliated_mpa, mpa_defacto_class, mpa_defacto_designation, MHW, species)%>%
                        dplyr::summarize(total_counts = sum(counts))%>%
                        ungroup()%>%
                        pivot_wider(names_from = "species", values_from = "total_counts")%>%
                        mutate(group="kelp")


kelp_swath_mpa_year <- left_join(kelp_swath_mpa_year_step1, envr_dat, 
                                      by=c("year","group",
                                                       "region3","region4",
                                                       "mpa_defacto_class",
                                                       "mpa_defacto_designation",
                                                       "affiliated_mpa"="mpa_name"))%>%
                  dplyr::select(1:7,72:90,8:71) %>%
                  dplyr::select(!c("mpa_class","mpa_designation")) %>%
                  mutate(group = "kelp_swath")%>%
                  dplyr::select(group, everything()) 


#Export year level
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/ecological_community_data/year_level_with_envr_vars" 
#write.csv(kelp_swath_mpa_year, file.path(path_aurora, "kelp_swath_mpa_year.csv"), row.names = FALSE)

```


#process kelp forest upc data
```{r}
data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/monitoring_kelp"
input_file <- "MLPA_kelpforest_upc.4.csv" 
kelp_upc_counts <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names()%>%
                    filter(category=="COVER")


#select vars and clean
kelp_upc_counts1 <- kelp_upc_counts %>%
                    dplyr::select(year, site, zone, transect, classcode, count, pct_cov)%>%
                    group_by(year, site, zone, transect, classcode)


#join species names by class code 
input_file <- "MLPA_kelpforest_taxon_table.4.csv"  
kelp_taxon <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names() %>%
                    dplyr::select(classcode, species_definition) %>%
                    distinct() #remove duplicates

kelp_upc_counts2<-  left_join(kelp_upc_counts1, kelp_taxon, by="classcode")

kelp_upc_counts3 <- kelp_upc_counts2 %>%
                    dplyr::select(year, site, zone, transect, classcode, species=species_definition, count, pct_cov)

#drop data 
kelp_upc_counts4 <- kelp_upc_counts3 %>%
                    filter(!(species=="Haliotis"|
                               species=="Laminaria"|
                               species=="laminariales"|
                               species=="UCSC 2000 Definition Of 'Other Red' Included All Red Algae Except Rhospp, Bushy, Leafy, Crucor And Erecor"|
                               species=="UCSB 2000 Definition Of 'Other Red' Included All Red Algae Except Rhospp, Bushy, Leafy, Crucor And Erecor"|
                               species=="Red Alga With Cylindrical Branches. Definition Used In 2000"|
                              species=="UCSC and UCSB 1999 Definition Of 'Other Red' Included All Red Algae Except Rhospp, Crucor And Erecor"|
                               species=="Laminariales Holdfast (Alive)"|
                               species=="Sargassum"|
                               species=="Aglaophenia struthionides"|
                               species=="Macrosystis Holdfast (Dead)"|
                               species=="Bare Rock"|
                               species=="Bare Sand"|
                               species=="Unidentified Fish"|
                               species=="Actiniaria"|
                               species=="Shell Debris"|
                               species=="Sediment/Mud"))


#recalculate percent cov
kelp_upc_counts5 <- kelp_upc_counts4 %>%
                    group_by(year, site, zone, transect, classcode, species)%>%
                    dplyr::summarize(sum_count = sum(count)) 

#check to make sure UPC counts add up to ~30 per transect               
check_counts <- kelp_upc_counts4 %>%
                    group_by(year, site, zone, transect)%>%
                    dplyr::summarize(transect_total = sum(count))

#join percent cov with transect total
kelp_upc_counts6 <- left_join(kelp_upc_counts5, check_counts, by=c("year","site","zone","transect"))%>%
                    mutate(pct_cov = (sum_count / transect_total)*100)%>%
                    mutate_at(vars(pct_cov), round, 1)



#add affiliated_mpa

input_file <- "MLPA_kelpforest_site_table.4.csv" 
kelp_sites <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names() %>%
                    dplyr::select(site, ca_mpa_name_short, mpa_class=site_designation, mpa_designation=site_status)%>%
                    distinct() #remove duplicates

kelp_upc_counts <- left_join(kelp_upc_counts6, kelp_sites, by="site")

kelp_upc_counts <- kelp_upc_counts %>%
                    ungroup() %>%
                    dplyr::select(year, affiliated_mpa=ca_mpa_name_short,mpa_class, mpa_designation, zone, transect, classcode, species, pct_cov) %>%
                    mutate(mpa_designation = ifelse(mpa_designation=="reference","ref",mpa_class))



#add 4 regions
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
four_region <- readxl::read_excel(file.path(data_path, input_file), sheet=1, skip = 0, na="NA")

regions <- four_region %>%
  dplyr::select(name, region3=bioregion, region4 = four_region_north_ci)

kelp_upc_counts$affiliated_mpa <- tolower(kelp_upc_counts$affiliated_mpa)

kelp_upc_counts <- left_join(kelp_upc_counts, regions, by=c("affiliated_mpa"="name"))


#add defacto SMRs
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
defacto_smr <- readxl::read_excel(file.path(data_path, input_file), sheet=5, skip = 0, na="NA")%>%
               filter(group=="kelp") %>%
               dplyr::select(affiliated_mpa, mpa_class)
              

kelp_upc_counts <- left_join(kelp_upc_counts, defacto_smr, by="affiliated_mpa")

#final check for any odd cen coast species

kelp_spp_check <- kelp_upc_counts %>% filter(region3=='central')
unique(kelp_spp_check$species)

#clean up
kelp_upc_counts <- kelp_upc_counts %>%
                    mutate(mpa_defacto_designation = ifelse(mpa_designation=="ref","ref",mpa_class.y))%>%
                    dplyr::select(year, region3, region4, affiliated_mpa, mpa_defacto_class = mpa_class.y, mpa_defacto_designation, zone, transect, 
                                  classcode, species, pct_cov)
                 
kelp_upc_counts$mpa_defacto_class <- tolower(kelp_upc_counts$mpa_defacto_class)
kelp_upc_counts$mpa_defacto_designation <- tolower(kelp_upc_counts$mpa_defacto_designation)

kelp_upc_counts <- kelp_upc_counts %>%
                    group_by(year, region3, region4, affiliated_mpa, mpa_defacto_class, mpa_defacto_designation, species) %>%
                    dplyr::summarise(mean_pct_cov = mean(pct_cov)) #take transect levels means



#reshape to wide format
kelp_upc_mpa_year_step1 <- kelp_upc_counts %>%
                    pivot_wider(names_from=species, values_from=mean_pct_cov) %>%
                    janitor::clean_names()%>%
                    drop_na(region4) %>%
                    mutate(MHW = ifelse(year>=2014 & year<=2016, "during",ifelse(year<2014, "before","after")))%>%
                    dplyr::select(year, region3, region4, affiliated_mpa, mpa_defacto_class, MHW, everything())%>%
                    mutate(group='kelp')
                    #dplyr::select(-c(no_organisms_present_in_this_sample))


kelp_upc_mpa_year <- left_join(kelp_upc_mpa_year_step1, envr_dat, 
                               by=c("year","group",
                                                       "region3","region4",
                                                       "mpa_defacto_class",
                                                       "mpa_defacto_designation",
                                                       "affiliated_mpa"="mpa_name"))%>%
                  dplyr::select(1:7,80:98,8:79) %>%
                  dplyr::select(!c("mpa_class","mpa_designation")) %>%
                  dplyr::select(group, everything()) %>%
                  mutate(group=recode(group,kelp="kelp_upc")) %>%
                  mutate_at(c(25:96), ~replace_na(.,0))

#Export
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/ecological_community_data/year_level_with_envr_vars" 
#write.csv(kelp_upc_mpa_year,file.path(path_aurora, "kelp_upc_mpa_year.csv"), row.names = FALSE)


```



#process midwater/deep reef data
```{r}
#load species level mean fish biomass 
data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/monitoring_deep-reef/ROV_Dataset"
input_file <- "MidDepth_ROV_Fish_Count.csv" 
deep_reef_counts_raw <- read.csv(file.path(data_path, input_file)) %>%
                    janitor::clean_names()


#select vars and clean
deep_reef_counts <- deep_reef_counts_raw %>%
                    filter(!grepl('Unidentified',scientific_name), #remove anything not identified to the species level
                           !grepl('SMCA/Outside',type), #remove uncertain MPA types
                           !grepl('SMR/SMCA',type))%>%  #remove undertain MPA types
                    dplyr::select(year, mpa_group, type, designation, scientific_name, count)%>%
                    group_by(year, mpa_group, type, designation, scientific_name)%>%
                    dplyr::summarize(total_count = sum(count)) #counts in raw data are grouped by size class. Take summary across all sizes 

deep_reef_counts$mpa_group[deep_reef_counts$mpa_group == "N/A" ] <- NA     #replace missing data with NA and drop
deep_reef_counts <- deep_reef_counts %>%
                    drop_na(mpa_group)

deep_reef_counts$designation <- recode_factor(deep_reef_counts$designation, "MPA/Outside" = 'Reference')




#add affiliated_mpa
deep_reef_counts <- deep_reef_counts %>%
                    mutate(mpa_class = type,
                           affiliated_mpa = paste(mpa_group,type),
                           mpa_designation = ifelse(designation=='Reference','ref',type))%>%
                    ungroup()%>%
                    dplyr::select(year, affiliated_mpa, mpa_class, mpa_designation, scientific_name, total_count)
                    
deep_reef_counts$affiliated_mpa <- tolower(deep_reef_counts$affiliated_mpa)


#check for inconsistencies in mpa name spelling and correct designations

deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "se farallon islands smca" = "southeast farallon island smca") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "se farallon islands smr" = "southeast farallon island smr") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "n farallon islands smr" = "north farallon island smr") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "n farallon islands smca" = "north farallon island smr") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "north farallon island smr" = "north farallon islands smr") #correct spelling to match affiliated

deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "farallon islands smr" = "southeast farallon island smr") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "farallon islands smca" = "southeast farallon island smr") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "farnsworth smca" = "farnsworth offshore smca") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "point st. george smca" = "point st. george reef offshore smca") #correct spelling to match affiliated
deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "point buchon smr" = "Point Buchon") #correct spelling to match affiliated



#add defacto SMRs
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
defacto_smr <- readxl::read_excel(file.path(data_path, input_file), sheet=5, skip = 0, na="NA")%>%
               filter(group=="deep_reef") %>%
               dplyr::select(affiliated_mpa, mpa_class)

buchon_row <- c("Point Buchon","SMR","point buchon smr","No take.","deep_reef","SMR") 
defacto_smr <- rbind(defacto_smr,buchon_row) #add missing row
              
deep_reef_counts <- left_join(deep_reef_counts, defacto_smr, by="affiliated_mpa")


#clean
deep_reef_counts <- deep_reef_counts %>%
                    mutate(mpa_defacto_designation = ifelse(mpa_designation=='ref',mpa_designation,mpa_class.y))%>%
                    dplyr::select(year, affiliated_mpa,mpa_class=mpa_class.x, mpa_designation, mpa_defacto_class=mpa_class.y, mpa_defacto_designation=mpa_designation, scientific_name, total_count)

deep_reef_counts$scientific_name[deep_reef_counts$scientific_name == "" ] <- NA     #replace missing data with NA and drop

deep_reef_counts <- deep_reef_counts %>%
                    drop_na(scientific_name)

deep_reef_counts$mpa_defacto_class <- tolower(deep_reef_counts$mpa_defacto_class)
deep_reef_counts$mpa_defacto_designation <- tolower(deep_reef_counts$mpa_defacto_designation)


#add 4 regions
data_path <- "/home/shares/ca-mpa/data/sync-data/mpa_traits"
input_file <- "mpa-attributes.xlsx" 
four_region <- readxl::read_excel(file.path(data_path, input_file), sheet=1, skip = 0, na="NA")

regions <- four_region %>%
  dplyr::select(name, region3=bioregion, region4 = four_region_north_ci)

deep_reef_counts$affiliated_mpa <- recode_factor(deep_reef_counts$affiliated_mpa, "Point Buchon"="point buchon smr")

deep_reef_counts <- left_join(deep_reef_counts, regions, by=c("affiliated_mpa"="name"))

#clean
deep_reef_counts <- deep_reef_counts %>%
                    group_by(year, region3, region4, affiliated_mpa,mpa_class, mpa_defacto_class, mpa_defacto_designation, scientific_name) %>%
                    dplyr::summarise(counts = sum(total_count)) #make sure species are not duplicates by summarizing at the transect level (total counts)

#drop species per PI based on incorrect range or ID

deep_reef_counts_drop <- deep_reef_counts %>%
                         #drop from all regions
                         filter(!(scientific_name=='Hippoglossus stenolepis'|
                                  scientific_name=='Hypsypops rubicundus'|
                                  scientific_name=='Merluccius_productus'|
                                  scientific_name=='Sebastes rosenblatti'|
                                  scientific_name=='Ammodytes hexapterus'|
                                  scientific_name=='Anisotremus davidsonii'|
                                  scientific_name=='Pristigenys serrula'|
                                  scientific_name=='Mola mola'|
                                  scientific_name=='Alopias vulpinus'| 
                                  scientific_name=='Lythrypnus dalli'|
                                  scientific_name=='Brachyistius frenatus'|
                                  scientific_name=='Sebastes caurinus or carnatus'|
                                  scientific_name=='Sebastes pinniger or miniatus'|
                                  scientific_name=='Engraulis mordax'|
                                  scientific_name=='Aulorhynchus flavidus'|
                                  scientific_name=='Aulorhynchus flavidus'|
                                  scientific_name=='Sebastes serranoides or flavidus'|
                                  scientific_name=='Sebastes hopkinsi or entomelas'|
                                  scientific_name=='Sebastes melanops or mystinus or diaconus'|
                          #drop for north only
                                  scientific_name=='Pleuronichthys ritteri' &
                                      region4=='north' |
                                  scientific_name=='Hypsurus caryi' &
                                      region4=='north'|
                                  scientific_name=='Paralabrax nebulifer' &
                                      region4=='north'|
                                  scientific_name=='Sebastes umbrosus' &
                                      region4=='north'|
                                  scientific_name=='Phanerodon atripes' &
                                      region4=='north'|
                                  scientific_name=='Sebastes atrovirens' &
                                      region4=='north'|
                                  scientific_name=='Girella nigricans' &
                                      region4=='north'|
                                  scientific_name=='Paralabrax clathratus' &
                                      region4=='north'|
                                scientific_name=='Semicossyphus pulcher' &
                                      region4=='north'|
                                scientific_name=='Scorpaena guttata' &
                                      region4=='north'|
                                scientific_name=='Heterodontus francisci' &
                                      region4=='north'|
                                scientific_name=='Gymnothorax mordax' &
                                      region4=='north'|
                                scientific_name=='Cephaloscyllium entriosum' &
                                      region4=='north'|
                                scientific_name=='Seriola lalandi' &
                                      region4=='north'|
                                scientific_name=='Halichoeres semicinctus' &
                                      region4=='north'|
                        #drop for central
                                scientific_name=='Heterodontus francisci' &
                                      region4=='central'|
                                scientific_name=='Gymnothorax mordax' &
                                      region4=='central'|
                                scientific_name=='Cephaloscyllium ventriosum' &
                                      region4=='central'|
                                scientific_name=='Seriola lalandi' &
                                      region4=='central'|
                                scientific_name=='Halichoeres semicinctus' &
                                      region4=='central'|
                                scientific_name=='Anarrihichthys ocellatus' &
                                      region4=='central'|
                                scientific_name=='Chromis punctipinnis' &
                                      region4=='central'|
                                scientific_name=='Cymatogaster aggregata' &
                                      region4=='central'|
                                scientific_name=='Eopsetta jordani' &
                                      region4=='central'|
                                scientific_name=='Lepidopsetta bilineata' &
                                      region4=='central'|
                                scientific_name=='Medialuna californiensis' &
                                      region4=='central'|
                                scientific_name=='Microstomus pacificus' &
                                      region4=='central'|
                                scientific_name=='Sebastes goodei' &
                                      region4=='central'|
                                scientific_name=='Torpedo californica' &
                                      region4=='central'|
                                scientific_name=='Squalus acanthias' &
                                      region4=='central'|
                                scientific_name=='Anarrhichthys ocellatus' &
                                      region4=='central'|
                               scientific_name=='Schooling (10-15 cm Sebastes sp.)' &
                                      region4=='central'|
                          
                        #drop for south
                                scientific_name=='Enophrys bison' &
                                      region4=='south'|
                                scientific_name=='Platichthys stellatus' &
                                      region4=='south'|
                        #drop for n. islands
                                scientific_name=='Enophrys bison' &
                                      region4=='north islands'
                            )
                        )

#check cen coast spp

deep_reef_counts_drop_check <- deep_reef_counts_drop %>% filter(region3=='central')


#reshape to wide format
deep_reef_counts_wide <- deep_reef_counts_drop %>%
                    filter(region3=='central')%>%
                    pivot_wider(names_from=scientific_name, values_from=counts) %>%
                    janitor::clean_names()%>%
                    drop_na(region4) %>%
                    mutate(MHW = ifelse(year>=2014 & year<=2016, "during",ifelse(year<2014, "before","after")))%>%
                    dplyr::select(year, region3, region4, affiliated_mpa,mpa_class, mpa_defacto_class, mpa_defacto_designation, MHW, everything()) %>%
                    replace(is.na(.),0)%>%
                    mutate(group='deep_reef')
          
                    #dplyr::select(-c(no_organisms_present_in_this_sample))


deep_reef_counts_wide$mpa_class <- tolower(deep_reef_counts_wide$mpa_class)

#drop species that were never observed on the central coast
deep_reef_counts_wide_drop <- deep_reef_counts_wide %>% filter(region3=='central') %>%
                    select(!(where(~ any(. != 0))))

deep_reef_counts_wide1 <- deep_reef_counts_wide %>% filter(region3=='central') %>%
                    select(where(~ any(. != 0)))

#merge data

deep_reef_merge <- as.data.frame(deep_reef_counts_wide1) %>%
                  mutate(zaniolepis_frenata_or_latipinnis_merge = rowSums(
                    select(.,'zaniolepis_frenata_or_latipinnis',
                           'zaniolepis_latipinnis',
                           'zaniolepis_frenata')))%>%
                  select(!(c('zaniolepis_frenata_or_latipinnis',
                           'zaniolepis_latipinnis',
                           'zaniolepis_frenata')))%>%
                  rename(zaniolepis_frenata_or_latipinnis = zaniolepis_frenata_or_latipinnis_merge)


#clean up
deep_reef_counts_envr <- left_join(deep_reef_merge, envr_dat, 
                                  by=c("year","group",
                                                    "region3","region4",
                                                    "mpa_class"="mpa_class",
                                                    "mpa_defacto_designation"="mpa_designation",
                                                  "affiliated_mpa"="mpa_name")) %>%
                  dplyr::select(1:8,114:132,9:113) %>%
                  dplyr::select(!c("mpa_defacto_class.y","mpa_defacto_designation.y"),
                                mpa_defacto_class="mpa_defacto_class.x") %>%
                  dplyr::select(group, everything())

#Export
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/ecological_community_data/year_level_with_envr_vars" 
#write.csv(deep_reef_counts_envr,file.path(path_aurora, "deep_reef_mpa_year.csv"), row.names = FALSE)

```


#process intertidal data
```{r}
#
#load intertidal 
data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/monitoring_rocky-intertidal/Community analysis"
input_file <- "intertidal_site_counts.csv"
  
rocky_counts_raw <- read.csv(file.path(data_path, input_file)) %>%
                                janitor::clean_names()


#clean
rocky_counts_raw$affiliated_mpa <- tolower(rocky_counts_raw$affiliated_mpa)

rocky_counts_raw$mpa_designation <- tolower(rocky_counts_raw$mpa_designation)

rocky_counts_raw$mpa_designation <- recode_factor(rocky_counts_raw$mpa_designation,"none"="ref")

rocky_counts_raw <- rocky_counts_raw %>%
                    filter(!(mpa_designation=='sc')) %>%
                     mutate(year = (as.factor(year)))

rocky_counts_raw$site <- tolower(rocky_counts_raw$site) 

rocky_count_envr <- left_join(rocky_counts_raw, rocky_envr_vars, by=c("year","site"))%>%
  mutate(group="rocky")%>%
  select(year, group, region3, region4,site, mpa_designation, affiliated_mpa, 
         mpa_designation,59:74, 8:56)


#export
#path_aurora <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/ecological_community_data/year_level_with_envr_vars" 
#write.csv(rocky_count_envr, file.path(path_aurora, "rocky_mpa_year.csv"), row.names = FALSE)

```
















