---
title: "Untitled"
author: "Joshua G. Smith"
date: "2022-08-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---
title: "Untitled"
author: "Joshua G. Smith"
date: "2022-08-31"
output: html_document
---

#load required packages
```{r}
rm(list=ls())

#required packages
require(vegan)
require(dplyr)
require(tidyr)
require(gridExtra)
require(usedist)
require(ggplot2)
require(reshape2)
require(ggfittext)
require(mvabund)

```



#load data
```{r}
# #load data --------------------------------------------------------------

data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/ecological_community_data/year_level_with_envr_vars"

comm_data <- load(file.path(data_path, "comm_data.rda"))
group_vars <- load(file.path(data_path, "group_vars.rda"))
```


#test data
```{r}
dat_dir <- "/home/shares/ca-mpa/data/sync-data/monitoring/processed_data/ecological_community_data/year_level_with_envr_vars/"

CCFRP <- read.csv(file.path(dat_dir, "CCFRP_mpa_year.csv"))
kelp_swath <- read.csv(file.path(dat_dir, "kelp_swath_mpa_year.csv"))
kelp_upc <- read.csv(file.path(dat_dir, "kelp_upc_mpa_year.csv"))
kelp_combined <- read.csv(file.path(dat_dir, "kelp_swath_upc_mpa_year.csv"))
kelp_fish <- read.csv(file.path(dat_dir, "kelp_fish_mpa_year.csv"))
deep_reef <- read.csv(file.path(dat_dir, "deep_reef_mpa_year.csv"))
rocky <- read.csv(file.path("/home/shares/ca-mpa/data/sync-data/processed_data/ecological_community_data/year_level", "rocky_mpa_year.csv"))

```

#restrict analyses to cen coast
```{r}
CCFRP_cen <- CCFRP %>% filter(region4=='central') %>%
  select(where(~ any(. != 0)))
kelp_swath_cen <- kelp_swath %>% filter(region4=='central') %>%
  select(where(~ any(. != 0)))
kelp_upc_cen <- kelp_upc %>% filter(region4=='central') %>%
  select(where(~ any(. != 0)))
kelp_invalg <- kelp_fish %>% filter(region4=='central') %>%
  select(where(~ any(. != 0)))
kelp_fish_cen <- kelp_fish %>% filter(region4=='central') %>%
  select(where(~ any(. != 0)))
deep_reef_cen <- deep_reef %>% filter(region4=='central') %>%
  select(where(~ any(. != 0)))
rocky_cen <- rocky %>% filter(region4=='central') %>%
  select(where(~ any(. != 0)))
```


#test data transformations
```{r}
#CCFRP
CCFRP_process <- CCFRP_cen %>%
  rowwise() %>%
  dplyr::mutate(sum = sum(across(25:ncol(.)), na.rm = T)) %>% #check for any sites with all zeros
  filter(!(sum==0))%>% #then remove any sites will all zeros
  dplyr::select(-sum)%>%
  mutate(desig_state = paste(mpa_designation,MHW))%>%
  dplyr::select(desig_state, everything())%>%
  arrange(year, desig_state) #remove rows containing only zeros

#define grouping vars
CCFRP_group_vars <- CCFRP_process %>%
  dplyr::select(1:9)

#define envr vars
CCFRP_envr_vars <- CCFRP_process %>%
  dplyr::select(c(SST="sst_monthly_anom",CUTI="cuti_monthly_anom",BEUTI="beuti_monthly_anom",MOCI="annual_MOCI"))


#define data for ordination
CCFRP_ord_data <- CCFRP_process %>%
  dplyr::select(26:ncol(.))

#standardize to max
CCFRP_rel <- decostand(CCFRP_ord_data, method = "hellinger")

#generate a BC dissim matrix
CCFRP_distmat <- vegdist(CCFRP_rel, method = "bray", na.rm=T) 


#kelp swath and upc processing--------------------------------------------------

kelp_invalg <- kelp_combined %>%
  dplyr::select(-bare_rock,
                -bare_sand, -shell_debris, -group.y, group=group.x)%>%
  mutate(desig_state = paste(mpa_defacto_designation,MHW))%>%
  dplyr::select(desig_state, everything())%>%
  filter(mpa_defacto_designation=="smr" | mpa_defacto_designation=="ref")#drop sum columns and non-species categories

#define grouping vars
kelp_invalg_group_vars <- kelp_invalg%>%
  dplyr::select(1:9)

#define envr vars
kelp_invalg_envr_vars <-  kelp_invalg %>%
  dplyr::select(c(SST="sst_monthly_anom",CUTI="cuti_monthly_anom",BEUTI="beuti_monthly_anom",MOCI="annual_MOCI"))


#define data for ordination
kelp_invalg_ord_data <- kelp_invalg%>%
  ungroup()%>%
  dplyr::select(26:ncol(.))


# NOTE decstand(method = "max") already performed in Step 2


#generate a BC dissim matrix
kelp_invalg_distmat <- 
  vegdist(kelp_invalg_ord_data, method = "bray", na.rm=T) #generates a BC dissim matrix




#kelp fish processing---------------------------------------------------------

kelp_fish <- kelp_fish_cen %>%
  rowwise() %>%
  dplyr::mutate(sum = sum(across(25:ncol(.), na.rm = T))) %>%
  filter(!(sum==0))%>% #remove rows containing only zeros
  dplyr::select(-sum) %>%
  mutate(desig_state = paste(mpa_defacto_designation,MHW))%>%
  dplyr::select(desig_state, everything())%>%
  filter(mpa_defacto_designation=="smr" | mpa_defacto_designation=="ref")#drop sum columns and non-species categories  #drop sum columns and non-species categories


#define grouping vars
kelp_fish_group_vars <- kelp_fish %>%
  dplyr::select(1:9)

#define envr vars
kelp_fish_envr_vars <-  kelp_fish %>%
  dplyr::select(c(SST="sst_monthly_anom",CUTI="cuti_monthly_anom",BEUTI="beuti_monthly_anom",MOCI="annual_MOCI"))

#define data for ordination
kelp_fish_ord_data <- kelp_fish %>%
  ungroup() %>%
  dplyr::select(26:ncol(.))

#calculate relative abundance
kelp_fish_rel <- decostand(kelp_fish_ord_data, method = "hellinger")

#kelp_fish_rel <- kelp_fish_rel %>% slice_sample(n=2000) # testing if work on smaller

#generate a BC dissim matrix
kelp_fish_distmat <- 
  vegdist(kelp_fish_rel, method = "bray", na.rm=T) #generates a BC dissim matrix



#deep reef processing---------------------------------------------------------

deep_reef <- deep_reef_cen %>%
  rowwise() %>%
  dplyr::mutate(sum = sum(across(26:ncol(.), na.rm = T))) %>%
  filter(!(sum==0))%>% #remove rows containing only zeros
  dplyr::select(-c(sum, schooling_10_15_cm_sebastes_sp,
                   schooling_10_15_cm_sebastes_sp,
                   young_of_year_10_cm_sebastes_sp,
  ))%>%
  mutate(desig_state = paste(mpa_defacto_designation,MHW))%>%
  dplyr::select(desig_state, everything())%>%
  filter(mpa_defacto_designation=="smr" | mpa_defacto_designation=="ref") #drop sum columns and non-species categories

#define grouping vars
deep_reef_group_vars <- deep_reef%>%
  dplyr::select(1:10)

#define envr vars
deep_reef_envr_vars <-  deep_reef %>%
  dplyr::select(c(SST="sst_monthly_anom",CUTI="cuti_monthly_anom",BEUTI="beuti_monthly_anom",MOCI="annual_MOCI"))

#define data for ordination
deep_reef_ord_data <- deep_reef%>%
  ungroup()%>%
  dplyr::select(27:ncol(.))

#calculate relative abundance
deep_reef_rel <- decostand(deep_reef_ord_data, method="hellinger")

#generate a BC dissim mat
deep_reef_distmat <- 
  vegdist(deep_reef_rel, method = "bray", na.rm=T) #generates a BC dissim matrix



#Intertidal processing---------------------------------------------------------

rocky_count_envr$year <- as.numeric(as.character(rocky_count_envr$year))

rocky_counts <- #rocky_count_enr %>%
  rocky_count_envr %>%
  mutate(MHW = ifelse(year>=2014 & year<=2016, "during",ifelse(year<2014, "before","after")))%>%
  mutate(desig_state = paste(mpa_designation,MHW))%>%
  dplyr::select(desig_state, MHW, everything())%>%
  dplyr::filter(region4=='central')


rocky_counts <- rocky_counts %>% filter(mpa_designation == "smr" | mpa_designation == 'ref') %>% droplevels()

#define grouping vars
rocky_group_vars <- rocky_counts%>%
  dplyr::select(1:9)

#define envr vars
rocky_envr_vars <-  rocky_counts %>%
  dplyr::select(c(SST="sst_monthly_anom",CUTI="cuti_monthly_anom",BEUTI="beuti_monthly_anom",MOCI="annual_MOCI"))

#define data for ordination
rocky_ord_data <- rocky_counts %>%
  ungroup() %>%
  dplyr::select(26:ncol(.))

#calculate relative abundance
rocky_rel <- vegan::decostand(rocky_ord_data, method = "hellinger")

#generate a BC dissim matrix
rocky_distmat <- 
  vegan::vegdist(rocky_rel, method = "bray", na.rm=T) #generates a BC dissim matrix




```




















