---
title: "CPFV Species CPUE-Dist from MPA"
author: "Shelby Ziegler"
date: '2022-10-06'
output: html_document
editor_options: 
  chunk_output_type: console
---


# Read data
################################################################################
```{r}
# Clear workspace
rm(list = ls())

# Packages
library(tidyverse)
theme_set(theme_classic())

# Directories
plotdir <- "analyses/2performance_fisheries/analyses/cpfv_logbooks/figures" 

# Read logbook data
data_orig <- readRDS("/Users/shelbyziegler/Desktop/CDFW_2000_2020_cpfv_logbook_data.Rds")

#blocks
blocks <- readRDS("analyses/2performance_fisheries/analyses/blocks/blocks_by_mlpa_region_w_mpa_stats.Rds")
```

Build data

```{r}
# Build data
################################################################################

# Logbooks use
data <- data_orig %>% 
  # Reliable points
  # Compute CPUE
  mutate(angler_hrs=n_fishers * hrs_fished,
         cpue=n_kept/angler_hrs)


data1<-left_join(data, blocks, by=c("block_id", "block_state", "block_type"))

data1<-data1%>%
  filter(mlpa_region=="South Coast" | mlpa_region=="Central Coast"|mlpa_region=="North Central Coast" | mlpa_region=="North Coast")

#create-sum N kept
data1<-data1%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))


```

Group data by MPA vs non-MPA blovk per region for plotting.

```{r}
p1<-ggplot(data1, aes(x=year, y=(n_kept/1000), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")
p1         

p2<-ggplot(data1, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")

p2

grid.arrange(p1, p2)


library(plotrix)
#Plot the total kept fish and CPUE before MPA and After MPA implementation
data2<-data1%>%
  group_by(year, mlpa_region, mpa_yn)%>%
  summarize(meankept=mean(n_kept), errorkept=std.error(n_kept), meancpue=mean(cpue), errorcpue=std.error(cpue))

sc<-data1%>%
  filter(mlpa_region=="South Coast")%>%
  mutate(implementation=ifelse(year>=2012, "After", "Before"))%>%
   group_by(mpa_yn, implementation)%>%
  summarize(meankept=mean(n_kept), errorkept=std.error(n_kept), meancpue=mean(cpue), errorcpue=std.error(cpue))

psc<-ggplot(sc, aes(x=implementation, y=meankept, fill=mpa_yn))+
  geom_bar(stat="identity", position=position_dodge(), color="black")+
  geom_errorbar(aes(ymax=meankept+errorkept, ymin=meankept-errorkept), position=position_dodge(1), width=0.2)+
  coord_flip()+
  scale_fill_discrete("Block type")+
  ylab("Fishes kept")+
  xlab("Implementation")+
  ggtitle("South Coast")
  
#Central coast
cc<-data1%>%
  filter(mlpa_region=="Central Coast")%>%
  mutate(implementation=ifelse(year>=2007, "After", "Before"))%>%
   group_by(mpa_yn, implementation)%>%
  summarize(meankept=mean(n_kept), errorkept=std.error(n_kept), meancpue=mean(cpue), errorcpue=std.error(cpue))

pcc<-ggplot(cc, aes(x=implementation, y=meankept, fill=mpa_yn))+
  geom_bar(stat="identity", position=position_dodge(), color="black")+
  geom_errorbar(aes(ymax=meankept+errorkept, ymin=meankept-errorkept), position=position_dodge(1), width=0.2)+
  coord_flip()+
  scale_fill_discrete("Block type")+
  ylab("Fishes kept")+
  xlab("Implementation")+
  ggtitle("Central Coast")

ncc<-data1%>%
  filter(mlpa_region=="North Central Coast")%>%
  mutate(implementation=ifelse(year>=2010, "After", "Before"))%>%
   group_by(mpa_yn, implementation)%>%
  summarize(meankept=mean(n_kept), errorkept=std.error(n_kept), meancpue=mean(cpue), errorcpue=std.error(cpue))

pncc<-ggplot(ncc, aes(x=implementation, y=meankept, fill=mpa_yn))+
  geom_bar(stat="identity", position=position_dodge(), color="black")+
  geom_errorbar(aes(ymax=meankept+errorkept, ymin=meankept-errorkept), position=position_dodge(1), width=0.2)+
  coord_flip()+
  scale_fill_discrete("Block type")+
  ylab("Fishes kept")+
  xlab("Implementation")+
  ggtitle("North Central Coast")

nc<-data1%>%
  filter(mlpa_region=="North Coast")%>%
  mutate(implementation=ifelse(year>=2012, "After", "Before"))%>%
   group_by(mpa_yn, implementation)%>%
  summarize(meankept=mean(n_kept), errorkept=std.error(n_kept), meancpue=mean(cpue), errorcpue=std.error(cpue))

pnc<-ggplot(nc, aes(x=implementation, y=meankept, fill=mpa_yn))+
  geom_bar(stat="identity", position=position_dodge(), color="black")+
  geom_errorbar(aes(ymax=meankept+errorkept, ymin=meankept-errorkept), position=position_dodge(1), width=0.2)+
  coord_flip()+
  scale_fill_discrete("Block type")+
  ylab("Fishes kept")+
  xlab("Implementation")+
  ggtitle("North Coast")


grid.arrange(psc, pcc, pncc, pnc)
```
             
Extract data and plot Warm Water targered species: Rockfish, Lingcod, Cabezon

```{r}
#Statewide species
dataR<-data1%>%
  filter(comm_name=="Unspecified rockfish")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))
  
pR<-ggplot(dataR, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
    ggtitle("Unspecified rockfishes")
pR 

pR2<-ggplot(dataR, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("Unspecified rockfishes")
pR2


dataL<-data1%>%
  filter(comm_name=="Lingcod")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))

pL<-ggplot(dataL, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
  ggtitle("Lingcod")
pL 

pL2<-ggplot(dataL, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("Lingcod")
pL2


dataC<-data1%>%
   filter(comm_name=="Cabezon")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))

pC<-ggplot(dataC, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
  ggtitle("Cabezon")
pC

pC2<-ggplot(dataC, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("Cabezon")
pC2

library(gridExtra)
grid.arrange(pR, pL, pC)
grid.arrange(pR2, pL2, pC2)


```

Extract data and plot Warm Water targered species: Ocean whitefish, Sheephead, Kelp Bass

```{r}
### South Coast Species
dataSC<-data1%>%
  filter(mlpa_region=="South Coast" | mlpa_region=="Central Coast")

#Ocean whitefish
dataO<-dataSC%>%
   filter(comm_name=="Ocean whitefish")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))

pO<-ggplot(dataO, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
  ggtitle("Ocean whitefish")
pO

pO2<-ggplot(dataO, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("Ocean whitefish")
pO2

#California sheephead
dataS<-dataSC%>%
   filter(comm_name=="California sheephead")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))

pS<-ggplot(dataS, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
  ggtitle("California sheephead")
pS

pS2<-ggplot(dataS, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("California sheephead")
pS2



#Kelp bass
dataK<-dataSC%>%
   filter(comm_name=="Kelp bass")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))

pK<-ggplot(dataK, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
  ggtitle("Kelp bass")
pK

pK2<-ggplot(dataK, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("Kelp Bass")
pK2


grid.arrange(pO, pS, pK)
grid.arrange(pO2, pS2, pK2)
```

Extract and plot tunas which are not expected to be influenced by MPAs.

```{r}
### Tunas

#Yellowtail
dataY<-data1%>%
   filter(comm_name=="Yellowtail")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))

pY<-ggplot(dataY, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
  ggtitle("Yellowtail")
pY

pY2<-ggplot(dataY, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("Yellowtail")
pY2

#Blue fin
dataBF<-data1%>%
   filter(comm_name=="Bluefin tuna")%>%
  group_by(mlpa_region, year)%>%
  mutate(sum_kept=sum(n_kept))

pBF<-ggplot(dataBF, aes(x=year, y=(n_kept/1000), fill=mpa_yn))+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Thousands of fish kept")+
  facet_wrap(~mlpa_region, ncol=4, scales="free_y")+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete("Block type")+
  ggtitle("Bluefin")
pBF

pBF2<-ggplot(dataBF, aes(x=year, y=(n_kept/sum_kept), fill=mpa_yn),color="black")+ 
  geom_bar(stat="identity")+
  xlab("Year")+
  ylab("Proportion of fish kept")+
  facet_wrap(~mlpa_region, ncol=4)+
  theme(plot.title = element_text(size = 16, face = "bold"))+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  scale_fill_discrete(name="Block type")+
    ggtitle("Bluefin")
pBF2



grid.arrange(pY, pBF)
grid.arrange(pY2, pBF2)

```

Block counterfactuals

```{r}
blockcf<-readRDS("analyses/2performance_fisheries/analyses/blocks/block_counterfactual_key.Rds")


```


