---
title: "counterfactual analysis"
author: "Cori Lopazanski"
date: '2022-07-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(tidyverse)
library(MatchIt)
```

## 1. Check covariate balance

Values of standardized mean differences and eCDF statistics close to zero and values of variance ratios close to one indicate good balance, and here many of them are far from their ideal values.

```{r}
# Covariate balance
m.out0 <- matchit(block_treatment ~ block_area_km2 + block_mean_depth_fa + 
                    distance_to_shore_km + dist_to_port_km,
                  data = data3, method = NULL, distance = "glm")
summary(m.out0)
```

### Matching

```{r}
m.out2 <- matchit(block_treatment ~ block_area_km2 + block_mean_depth_fa + 
                    distance_to_shore_km + dist_to_port_km,
                  data = data3, 
                  method = "nearest", 
                  distance = "glm")
summary(m.out2)

summary(m.out2, un = FALSE)

plot(m.out2, type = "jitter", interactive = FALSE)

plot(m.out2, type = "qq", interactive = FALSE)

plot(summary(m.out2))
```

### Matching with added proximity

```{r}
m.out3 <- matchit(block_treatment ~ block_area_km2 + block_mean_depth_fa + 
                    distance_to_shore_km + dist_to_port_km + block_lat_dd + block_long_dd,
                  data = data4, 
                  method = "nearest", 
                  distance = "glm")
summary(m.out3)

summary(m.out3, un = FALSE)

plot(m.out3, type = "jitter", interactive = FALSE)

plot(m.out3, type = "qq", interactive = FALSE)

plot(summary(m.out3))
```


# Once with replacement or not

```{r}
m.out4 <- matchit(block_treatment ~ block_area_km2 + block_mean_depth_fa + 
                    distance_to_shore_km + dist_to_port_km + block_lat_dd + block_long_dd,
                  data = data4, 
                  method = "full", 
                  distance = "glm")
summary(m.out4)

plot(m.out4, type = "jitter", interactive = FALSE)

plot(m.out4, type = "qq", interactive = FALSE)

plot(summary(m.out4))
```
```{r}


```

