---
title: "means-map"
author: "Julien Brun"
knit: (function(input_file, encoding) {
  out_dir <- '../docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'means_maps.html'))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(purrr)
library(sf)
library(tmap)
library(RColorBrewer)
```

## Reading the data

```{r paths}

# Define the paths and file names

path_aurora <- "/home/shares/ca-mpa/data/sync-data/"
shp_dir <- "spatial_data"
cencoos_dir <- "CeNCOOS_shapefiles/Ecological_Monitoring_Sites"
shp_path <- file.path(path_aurora, shp_dir)

shp_ca <- file.path(path_aurora, shp_dir, "ca_boundary_wgs84.shp")


metrics_file_all <- "processed_data/peformance_metrics_meta_all.csv" 
metrics_file_1619 <- "processed_data/peformance_metrics_meta_1619.csv" 

map_file <- "Ecol_perform_metrics_means_4regions.geojson"


```


# Read the input files


```{r read inputs, message=FALSE, warning=FALSE}

# Load the 4 regions geospatial habitat data
st_perform_metrics_ci <- st_read(dsn = file.path(path_aurora, cencoos_dir, "sampling_sites_4regions.geojson")) 

# Removing the years and other info
st_perform_metrics <- st_perform_metrics_ci %>% 
  select(affiliated_mpa, group, mlpa_region, mpa_class, mpa_designation, variable, indicator, mpa.year) %>%
  distinct_all()

# load the performance metrics for all years
map_attributes_all <- read_csv(file.path(path_aurora, metrics_file_all))


# load the performance metrics for 2016-19
map_attributes_1619 <- read_csv(file.path(path_aurora, metrics_file_1619)) 


# Read California border
ca <- st_read(shp_ca)
# st_crs(ca)


# st_perform_metrics <- perform_metrics %>% 
#   st_as_sf(.,coords=c("lon_wgs84", "lat_wgs84"), crs=4326)

```
## Check things out

```{r  message=FALSE, warning=FALSE}
tm_reg4 <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
tm_shape(st_perform_metrics) + 
  tm_symbols(col = "mlpa_region",  alpha = 0.8, border.lwd = 0, size = .2, title.col = "Main Regions")

tm_reg4

```
## Join the  the stats


```{r}
st_perform_metrics_all <- left_join(st_perform_metrics_ci, map_attributes_all, by = c("group", "affiliated_mpa", "mlpa_region", "mpa_class", "variable", "indicator")) %>%
  mutate(mlpa_region = factor(mlpa_region, levels = c("north","central","island","south")))
```


## Difference in means


```{r  message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_all <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
tm_shape(st_perform_metrics_all[!is.na(st_perform_metrics_all$RR),]) + 
  tm_symbols(col = "mean_diff",  alpha = 0.5, border.lwd = 0, size = .3, title.col = "Diff. Means", palette = "Spectral", style = "quantile") 

tm_all

tmap_save(tm_all, filename = "../figs/mpa_means_all.png")
```


```{r}
tmap_mode("plot")

tm_nc <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
tm_shape(st_perform_metrics_all[!is.na(st_perform_metrics_all$RR),]) + 
  tm_symbols(col = "mean_diff",  alpha = 0.8, border.lwd = 0, size = .5, title.col = "Main Regions", palette = "Spectral", style = "quantile") + 
  tm_facets(by = "mlpa_region", ncol = 4, free.coords = T, inside.original.bbox = F)

tm_nc

tmap_save(tm_nc, filename = "../figs/mpa_means_nc.png")
```

## Log Ratios

```{r  message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_all <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
# tm_shape(st_perform_metrics_all[is.na(st_perform_metrics_all$RR),]) +
#                  tm_dots(shape=4, size = 0.5, border.lwd = 0.5) +
tm_shape(st_perform_metrics_all[!is.na(st_perform_metrics_all$RR),]) + 
  tm_symbols(col = "RR",  alpha = 0.5, border.lwd = 0, size = .3, title.col = "log Ratio", palette = "Spectral", style = "quantile") 

tm_all

tmap_save(tm_all, filename = "../figs/mpa_RR_all.png")
```

```{r  message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_nc <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
tm_shape(st_perform_metrics_all[!is.na(st_perform_metrics_all$RR),]) + 
  tm_symbols(col = "RR",  alpha = 0.8, border.lwd = 0, size = .5, title.col = "Main Regions", palette = "Spectral", style = "quantile") + 
  tm_facets(by = "mlpa_region", ncol = 4, free.coords = T, inside.original.bbox = F)

tm_nc

tmap_save(tm_nc, filename = "../figs/mpa_RR_nc.png")
```

```{r  message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_is <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
tm_shape(st_perform_metrics_all[!is.na(st_perform_metrics_all$RR),] %>% filter(mlpa_region %in% c("island", "south"))) + 
  tm_symbols(col = "RR",  alpha = 0.8, border.lwd = 0, size = .5, title.col = "Main Regions", palette = "Spectral", style = "quantile") + 
  tm_facets(by = "mlpa_region",  free.coords = T)

tm_is

tmap_save(tm_is, filename = "../figs/mpa_RR_is.png")

```

## Diversity
```{r  message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_all <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
tm_shape(st_perform_metrics_all[!is.na(st_perform_metrics_all$cohens_d),]) + 
  tm_symbols(col = "cohens_d",  alpha = 0.8, border.lwd = 0, size = .3, title.col = "Cohen’s d", palette = "-plasma", style = "quantile") 

tm_all

tmap_save(tm_all, filename = "../figs/mpa_cohend_all.png")
```


```{r  message=FALSE, warning=FALSE}
tmap_mode("plot")

tm_nc <- tm_shape(ca) + 
  tm_borders("black", lwd = .5) +
tm_shape(st_perform_metrics_all[!is.na(st_perform_metrics_all$RR),]) + 
  tm_symbols(col = "cohens_d",  alpha = 0.8, border.lwd = 0, size = .5, title.col = "Main Regions", palette = "Spectral", style = "quantile") + 
  tm_facets(by = "mlpa_region", ncol = 4, free.coords = T, inside.original.bbox = F)

tm_nc

tmap_save(tm_nc, filename = "../figs/mpa_cohen_nc.png")
```


