---
title: "tbd"
author: "Cori Lopazanski"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read Data 

```{r message = FALSE}
data_path <- "/home/shares/ca-mpa/data/sync-data"
input_file <- "Ecol_perform_metrics_means.xlsx" 

means <- readxl::read_excel(file.path(data_path, input_file), 
                            sheet=1, na = c("NA", "."), trim_ws = T)
```

## Manually Calculate T Score and P Value

Reformat the data by the affiliated MPA to calculate the difference in means between the MPA and its reference sites.

```{r}
## Cleaning
means_format <- means %>% 
  mutate(mpa_designation = if_else(mpa_designation %in% c("reference", "REF"), "REF", "MPA")) %>% 
  filter(!(group %in% c("rocky-bio", "rocky-LT"))) %>% 
  pivot_wider(id_cols = c(affiliated_mpa, group, mlpa_region, variable, indicator, year),
              names_from = mpa_designation,
              values_from = c(mean, sd, n)) %>% 
  drop_na()

# Dataframe that calculates mean difference, t-score, etc.
means_t <- means_format %>% 
  mutate(mean_diff = mean_MPA-mean_REF,
         se        = sqrt((sd_MPA^2/n_MPA)+(sd_REF^2/n_REF)),
         t_score   = mean_diff/se,
         df        = n_MPA + n_REF - 2,
         p_value   = pt(t_score, df, lower.tail = FALSE),
         sig       = if_else(p_value < 0.05, 1, 0),
         cohens_d  = abs(mean_diff)/(sqrt(((sd_MPA^2*(n_MPA-1))+(sd_REF^2*(n_REF-1)))/df)),
         log_RR    =  log10(mean_MPA/mean_REF))
        

```

# Some Rough Exploratory Plots

```{r}
t_significance <- means_t %>% 
  filter(indicator %in% c("shannon", "Diversity")) %>% 
  filter(year == 2019) %>% 
  group_by(affiliated_mpa, group, mlpa_region, indicator, variable) %>% 
  summarize(n_sig = sum(sig, na.rm = TRUE))


ggplot(data = means_t %>% 
        filter(indicator %in% c("shannon", "Diversity")) %>% 
         filter(se > 0) %>% 
         filter(year == 2019)) +
  geom_point(aes(x = year, y = mean_diff, color = sig)) +
  facet_wrap(~group+mlpa_region, scales = "free")


ggplot(data = means_t %>% 
         filter(se > 0)) +
  geom_point(aes(x = year, y = mean_diff, color = sig)) +
  facet_wrap(~group+mlpa_region)


ggplot(data = means_t %>% 
         filter(group == "CCFRP" & variable == "All Fish" & mlpa_region == "Central")) +
  geom_point(aes(x = year, y = mean_diff, color = sig)) +
  # scale_color_manual(values = c("blue4", "dodgerblue")) +
  facet_wrap(~indicator)

  
ccfrp <- means_t %>% 
  filter(group == "CCFRP" & variable == "All Fish" & mlpa_region == "Central")

ggplot(data = means_t %>% 
         filter(affiliated_mpa == "Point Lobos SMR") %>% 
         filter(indicator %in% c("shannon", "Diversity"))) +
  geom_point(aes(x = year, y = mean_diff, color = sig)) +
  facet_wrap(~group+indicator, scales = "free")

```


```{r}
ggplot(data = means_t %>% 
         filter(se > 0)) +
  geom_point(aes(x = year, y = cohens_d, color = sig)) +
  facet_wrap(~group)
  
```

- Consider following similar methods but aggregating across years
- Slicing the data in a more informative way (e.g. all fish)
