---
title: "Performance metrics"
author: "Julien Brun"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'performance_metrics.html'))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(tidytext)
```

```{r}
data_path <- "/home/shares/ca-mpa/data/sync-data"
input_file <- "Ecol_perform_metrics_means_4regions.csv" 
output_path = file.path(data_path, "processed_data")

means_data <- read.csv(file.path(data_path, input_file))
means_data$mpa_class <- recode_factor(means_data$mpa_class, none="ref")
```


```{r diversity}


#======Log Ratios for 2016-2019======

#This code takes the mean across all years and calculates sd across 2016-2019 years (each MPA/yr is a single rep)

region_yr_means_1619 <- means_data %>%
  filter(variable == "all species" | variable =="all fish"| variable =="invalg",
         indicator == "diversity",
         mpa_class == "ref"| mpa_class =="smr",
         year  == '2016' | year=='2017' | year=='2018' | year=='2019') %>%
  group_by(group, mlpa_region, mpa_designation, variable, indicator) %>%
  dplyr::summarize(yr.mean = mean(mean, na.rm=TRUE), 
                   sd=sd(mean, na.rm=TRUE), # standard deviation of across MPAs where indicator was observed/recorded
                   n=n()) %>%
  pivot_wider(names_from = mpa_designation,
              values_from = c(yr.mean, sd, n)
  )


#means by MPA

mu_site_1619 <- region_yr_means_1619 %>% 
  mutate(mean_diff = yr.mean_smr-yr.mean_ref,
         se        = sqrt((sd_smr^2/n_ref)+(sd_ref^2/n_ref)),
         HedgeG    = sqrt((sd_smr^2/(n_smr*yr.mean_smr))+(sd_ref^2/(n_ref*yr.mean_ref))),
         t_score   = mean_diff/se,
         df        = n_smr + n_ref - 2,
         p_value   = pt(t_score, df, lower.tail = FALSE),
         sig       = if_else(p_value < 0.05, 1, 0),
         cohens_d  = abs(mean_diff)/(sqrt(((sd_smr^2*(n_smr-1))+(sd_ref^2*(n_ref-1)))/df)),
         RR        = log(yr.mean_smr/yr.mean_ref),
         n_total   = n_smr + n_ref
         #lower.CI  = log((RR - (qt(0.975, df)*n_total/sqrt(n_total))+1)+1),
         #upper.CI  = log((RR + (qt(0.975, df)*n_total/sqrt(n_total)))+1)
  )



```






```{r log ratios all}

#======Log Ratios across all years======
#This code takes the mean across all years and calculates sd across all years (each MPA/yr is a single rep)

region_yr_means_all <- means_data %>%
  filter(variable=="all species" | variable=="all fish" | variable=="invalg",
         indicator == "diversity",
         mpa_class == "ref" | mpa_class =="smr") %>%
  group_by(group, mlpa_region, mpa_designation, variable, indicator)%>%
  dplyr::summarize(yr.mean = mean(mean, na.rm=TRUE), 
                   sd = sd(mean, na.rm=TRUE), # standard deviation of across MPAs where indicator was observed/recorded
                   n = n()) %>%
  pivot_wider(names_from = mpa_designation,
              values_from = c(yr.mean, sd, n)
  )


#means by MPA

mu_site_all <- region_yr_means_all %>% 
  mutate(mean_diff = yr.mean_smr-yr.mean_ref,
         se        = sqrt((sd_smr^2/n_ref)+(sd_ref^2/n_ref)),
         HedgeG    = sqrt((sd_smr^2/(n_smr*yr.mean_smr))+(sd_ref^2/(n_ref*yr.mean_ref))),
         t_score   = mean_diff/se,
         df        = n_smr + n_ref - 2,
         p_value   = pt(t_score, df, lower.tail = FALSE),
         sig       = if_else(p_value < 0.05, 1, 0),
         cohens_d  = abs(mean_diff)/(sqrt(((sd_smr^2*(n_smr-1))+(sd_ref^2*(n_ref-1)))/df)),
         RR        = log(yr.mean_smr/yr.mean_ref),
         n_total   = n_smr + n_ref
         #lower.CI  = log((RR - (qt(0.975, df)*n_total/sqrt(n_total))+1)+1),
         #upper.CI  = log((RR + (qt(0.975, df)*n_total/sqrt(n_total)))+1)
  )





```

## Write output files

```{r outputs, eval=FALSE}

# Write performance metrics for 2016 to 2019
write_csv(mu_site_1619, file.path(output_path, "peformance_metrics_meta_1619.csv"))

# Write performance metrics for all years
write_csv(mu_site_all, file.path(output_path, "peformance_metrics_meta_all.csv"))

```

