---
title: "Taxonomy Overlap"
author: "Cori Lopazanski"
date: '2022-05-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup 
```{r}
data_path <- "/home/shares/ca-mpa/data/sync-data/monitoring/taxonomy_tables"

library(tidyverse)
library(janitor)
library(here)
library(kableExtra)

```

# Read Taxonomy Tables
```{r}
ccfrp <- readxl::read_excel(here::here(data_path, "CCFRP_Taxonomy.xlsx"), 
                            sheet = 2,
                            na = "NA") %>% clean_names() %>% 
  mutate(group = "ccfrp")

dr <- readxl::read_excel(here::here(data_path, "DeepReef-ROV-Taxonomy.xlsx"),
                         na = "NA") %>% clean_names() %>% 
  mutate(group = "deep_reef")

rocky_bio <- readxl::read_excel(here::here(data_path, "RockyIntertidal-Biodiversity-Taxonomy.xlsx"),
                                na = "NA") %>% clean_names() %>% 
  mutate(group = "rocky_bio")

rocky_lt <- readxl::read_excel(here::here(data_path, "RockyIntertidal-LongTerm-Taxonomy.xlsx"),
                               na = "NA") %>% clean_names() %>% 
  mutate(group = "rocky_lt")

kf <- readxl::read_excel(here::here(data_path, "Kelp-Taxonomy.xlsx"),
                         na = "NA") %>% clean_names() %>% 
  mutate(group = "kelp_forest")

sb_seine <- read_csv(here::here(data_path, "SandyBeach-SurfZone-FishSeine-Taxonomy.csv"),
                     na = "NA") %>% clean_names() %>% 
  mutate(group = "sandy_beach_seine")

sb_bruv  <- read_csv(here::here(data_path, "SandyBeach-SurfZone-Bruv-Taxonomy.csv"),
                     na = "NA") %>% clean_names() %>% 
  mutate(group = "sandy_beach_bruv") 
```
# Goal 1: Create table which codes species as targeted and non-targeted

## Select columns from each individual taxonomy table
```{r}
ccfrp_tar <- ccfrp %>% 
  select(group, species_code, scientific_name, fished) %>% 
  rename(targeted = fished) 

ccfrp_tar$targeted[is.na(ccfrp_tar$targeted)] <- "NoData"

dr_tar <- dr %>% 
  select(group, pisco_code, scientific_name, targeted) %>% 
  rename(species_code = pisco_code)

dr_tar$targeted[is.na(dr_tar$targeted)] <- "NoData"

rocky_bio_tar <- rocky_bio %>% 
  select(group, species_code, species) %>% 
  rename(scientific_name = species) %>% 
  mutate(targeted = NA)

rocky_lt_tar <- rocky_lt %>% 
  select(group, marine_species_code, species) %>% 
  rename(species_code = marine_species_code,
         scientific_name = species)%>% 
  mutate(targeted = NA)

kf_tar <- kf %>% 
  select(group, pisco_classcode, scientific_name_accepted, targeted) %>% 
  rename(species_code = pisco_classcode,
         scientific_name = scientific_name_accepted)

kf_tar$targeted[is.na(kf_tar$targeted)] <- "NoData"


sb_bruv_tar <- sb_bruv %>% 
  select(group, species_code, species_definition, targeted) %>% 
  rename(scientific_name = species_definition) 

sb_bruv_tar$targeted[is.na(sb_bruv_tar$targeted)] <- "NoData"


sb_seine_tar <- sb_seine %>% 
  select(group, species_code, scientific_name_accepted, targeted) %>% 
  rename(scientific_name = scientific_name_accepted) %>% 
  filter(!is.na(scientific_name))

sb_seine_tar$targeted[is.na(sb_seine_tar$targeted)] <- "NoData"


```


## Join All Groups Together

```{r}
tar <- rbind(ccfrp_tar,
                  dr_tar,
                  kf_tar,
                  sb_bruv_tar,
                  sb_seine_tar)

tar$targeted[tar$targeted == "Nontargeted"] <- "Non-targeted"
tar$targeted[tar$targeted == "?"] <- "NoData"

# Test for duplicates
tar_dupl <- tar %>%
  group_by(scientific_name, group) %>% 
  summarize(n = dplyr::n(), .groups = "drop") %>% 
  filter(n > 1L)

# Remove duplicates
tar <- tar %>% 
  distinct(scientific_name, group, .keep_all = TRUE)
```

## Widen Table by Scientific Name

```{r}
tar_overlap <- tar %>%
  pivot_wider(id_cols = scientific_name, 
              names_from = group,
              values_from = targeted) %>% 
  replace(.=="NULL", NA) %>% 
  arrange(scientific_name)

```

## Export Table

```{r}
options(knitr.kable.NA = "")

names(tar_overlap) <- c("Scientific Name", "CCFRP", "Deep Reef", "Kelp Forest",
        "Sandy Beach (BRUV)", "Sandy Beach (Seine)") 

kbl(tar_overlap) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F, fixed_thead = T) %>% 
  save_kable(here::here("subteam-analyses",
                        "ltm-overlap",
                        "targeted-species-table.html"))
```


# Goal 2: Create one Species Table 

## Identify Common Variables

```{r}
sb <- sb_seine %>% 
  select(species_code:family, trophic_group:notes_trophic_targeted, feeding_mode, group) %>% 
  full_join(sb_bruv)


```






# Old
## Join by Scientific Name (or for rocky, "species")

```{r}
ccfrp_sp <- ccfrp %>% select(scientific_name)
dr_sp <- dr %>% select(scientific_name)
rocky_bio_sp <- rocky_bio %>% select(species)
rocky_lt_sp <- rocky_lt %>% select(species)
kf_sp <- kf %>% select(scientific_name_accepted)


taxa_overlap <- ccfrp_sp %>% 
  filter(scientific_name %in% rocky_lt_sp$species) # 1 Rocky LT with CCFRP 

taxa_overlap <- ccfrp_sp %>% 
  filter(scientific_name %in% dr_sp$scientific_name) %>% 
  unique() # 69 CCFRP and Deep Reef

taxa_overlap <- ccfrp_sp %>% 
  filter(scientific_name %in% kf_sp$scientific_name_accepted) %>% 
  unique() # 66 CCFRP and KF

taxa_overlap <- ccfrp_sp %>% 
  filter(scientific_name %in% kf_sp$scientific_name_accepted) %>% 
  filter(scientific_name %in% dr_sp$scientific_name) %>% 
  unique() # 55 CCFRP and KF and Deep Reef (18 are rockfishes)



```

