---
title: "Habitat Attributes - NMDS Approach"
author: "Cori Lopazanski"
date: '2022-06-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Set Up

```{r}
# Packages 
library(tidyverse)
library(vegan)
library(gdata)

# Directories
base.dir <- "/Volumes/GoogleDrive-105151121202188525604/Shared drives/NCEAS MPA network assessment/MPA Network Assessment: Working Group Shared Folder/data/sync-data" # Cori Local
att.dir <- here::here(base.dir, "mpa_traits", "processed")
int.dir <- file.path(getwd(), "analyses", "7habitat", "intermediate_data")

# Read Attribute (Habitat) Data
att_raw <- read_csv(file.path(att.dir, "mpa_attributes_clean.csv"))

```

## Build Attribute Data

### Select habitat variables from attribute data. 

```{r}
att_data <- att_raw %>% 
  # Combine predicted and mapped columns for 0-30m
  mutate(hard_substrate_0_30m_km2_comb = hard_substrate_predicted_0_30m_km2 + hard_substrate_mapped_0_30m_km2,
         soft_substrate_0_30m_km2_comb = soft_substrate_0_30m_km2 + soft_substrate_predicted_0_30m_km2) %>% 
  # Select variables for inclusion in NMDS
  select(name,
         region = four_region_north_ci,
         size_km2,
         sandy_beach_km,
         rocky_inter_km,
         max_kelp_canopy_cdfw_km2,
         hard_substrate_0_30m_km2_comb,
         hard_substrate_30_100m_km2,
         hard_substrate_100_200m_km2,
         hard_substrate_200_3000m_km2,
         soft_substrate_0_30m_km2_comb,
         soft_substrate_30_100m_km2,
         soft_substrate_100_200m_km2,
         soft_substrate_200_3000m_km2,
         submarine_canyon_0_30m_km2,
         submarine_canyon_30_100m_km2,
         submarine_canyon_100_200m_km2,
         submarine_canyon_200_3000m_km2,
         estuary_km2,
         surfgrass_km,
         eelgrass_km2,
         coastal_marsh_km2)

names(att_data)
```
### Format for NMDS analysis

```{r}
# Update rownames for NMDS
att_data_nmds <- att_data %>% 
  column_to_rownames("name") %>% 
  select(!region) 
  ## Will need to drop NAs later for NMDS most likely!

```

### Identify and remove estuaries

Examine which MPAs have estuarine characteristics and no offshore characteristics

```{r}
estuaries <- att_data_nmds %>% 
  filter_at(vars(estuary_km2, coastal_marsh_km2), any_vars(. > 0)) %>% 
  filter_at(vars(max_kelp_canopy_cdfw_km2:submarine_canyon_200_3000m_km2), all_vars(. == 0)) %>% 
  rownames_to_column("name")

estuaries$name
```

Remove estuary-only MPAs

```{r}
# Filter out the estuaries
att_noest <- att_data_nmds %>% 
  rownames_to_column("name") %>% 
  filter(!(name %in% estuaries$name)) %>% 
  column_to_rownames("name")
```


##  Create metadata df with name, region, class

```{r}
att_nmds_meta <- att_raw %>% 
  select(name, region = four_region_north_ci, mpa_class)

names(att_data)
abbrev_names <- c("name",
                  "region",
                  "size",
                  "beach",
                  "rocky",
                  "kelp",
                  "hard 0-30m",
                  "hard 30-100m",
                  "hard 100-200m",
                  "hard 200-3000m",
                  "soft 0-30m",
                  "soft 30-100m",
                  "soft 100-200m",
                  "soft 200-3000m",
                  "canyon 0-30m",
                  "canyon 30-100m",
                  "canyon 100-200m",
                  "canyon 200-3000m",
                  "estuary",
                  "surfgrass",
                  "eelgrass",
                  "marsh")

att_names <- data.frame(attribute = names(att_data),
                        att_short = abbrev_names)
```


## Export

```{r}
# Subset of MPA attributes (all MPAs)
saveRDS(att_data_nmds, file.path(int.dir, "mpa_attributes_nmds_subset.Rds"))

# Subset of MPA attributes with estuariy-only MPAs removed
saveRDS(att_noest, file.path(int.dir, "mpa_attributes_nmds_subset_no_estuaries.Rds"))

# Metadata - name, region, class
saveRDS(att_nmds_meta, file.path(int.dir, "mpa_attributes_nmds_metadata.Rds"))

# Attribute metadata (name labels)
saveRDS(att_names, file.path(int.dir, "mpa_attributes_labels.Rds"))
```







