---
title: "4-ROV"
author: "Cori Lopazanski"
date: '2022-07-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,	warning = FALSE)
```

## Setup

```{r}
# Packages
library(tidyverse)
library(vegan)

# Directories
int.dir <- file.path("analyses", "7habitat","intermediate_data")

# Read Data
## Attribute (Habitat) Data
att_data <- readRDS(file.path(int.dir, "mpa_attributes_nmds_subset.Rds"))

## ROV Community
rov_data <- readRDS(file.path(int.dir, "species_matrix_rov_1620.Rds")) 
```



```{r}
# Get attributes for MPAs in ROV dataset
rov_env <- att_data %>% 
  filter(name %in% rov_data$name)

# Safe metadata df with name, region
rov_meta <- rov_env %>% 
  select(name, region)

# Set up matrices for vegan analyses
rov <- rov_data %>% column_to_rownames("name")
rov_env <- rov_env %>% 
  column_to_rownames("name") %>% 
  select(!region)
```

### examine richness and diversity

```{r}
# rov fish richness
rov_sppr <- specnumber(rov)

# difference in richness between regions?
rov_sppr_aov <- aov(rov_sppr ~ region, data = rov_meta)
summary(rov_sppr_aov) # no diff

# kf fish diversity
rov_shan <- diversity(rov)

# difference in diversity between regions?
rov_shan_aov <- aov(rov_shan ~ region, data = rov_meta)
summary(rov_shan_aov) # no diff

# difference in species composition between regions?
rov_perm <- adonis2(rov ~ region, data = rov_meta)
rov_perm # no diff
```

### nmds

```{r}
# nmds of fish community
rov_mds <- metaMDS(rov, distance = "euclidean", trymax = 999)
rov_mds
stressplot(rov_mds)

# plot nmds of fish community
rov_df <- scores(rov_mds, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("name") %>% 
  full_join(rov_meta, by = "name")

rov_plot <- ggplot(rov_df,
                  aes(x = NMDS1, y = NMDS2,
                      color = region, shape = region)) +
  geom_point(size = 3, alpha = 0.5) +
  stat_ellipse(aes(color = region), linetype = 2)+
  labs(title = "ROV NMDS") + 
  theme_classic()
rov_plot
```

### envfit: species driving separation?

```{r}
# envfit - how do species contribute to dissimilarity
rov_fit <- envfit(rov_mds, rov, perm = 999)

rov_fit_pvals <- rov_fit$vectors$pvals %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  dplyr::rename("pvals" = ".") # some are drivers

# extract coordinates for each species
rov_fit_coords <- rov_fit %>% 
  scores(., display = "vectors") %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  full_join(., rov_fit_pvals, by = "species") %>% 
  filter(pvals < 0.05)

# plot
ggplot(rov_df, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = region,
                 shape = region),
             size = 3, alpha = 0.8) +
  geom_segment(data = rov_fit_coords, 
               aes(x = 0, xend = NMDS1,
                   y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.2, "cm")),
               col = "black") +
  geom_text(data = rov_fit_coords, aes(label = species), size = 3) +
  scale_x_continuous(limits = c(-0.55, 0.55)) +
  scale_y_continuous(limits = c(-0.55, 0.55)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  labs(title = "ROV",
       color = "",
       shape = "") + 
  theme_classic()

```

### bioenv: link environmental variables to community dissimilarity

```{r}
# bioenv how do env vars contribute to dissimilarity
rov_bioenv <- bioenv(comm = rov, env = rov_env)
rov_bioenv

# select best model
rov_model <- rov_bioenv$models[[rov_bioenv$whichbest]] 
rov_keep <- rov_model$best

# use envfit to get vectors for top model variables
rov_envfit <- envfit(rov_mds, rov_env[, rov_keep], perm = 999, na.rm = TRUE)

# extract coordinates for each attribute
rov_envfit_coords <- rov_envfit %>% 
  scores(., display = "vectors") %>% 
  as.data.frame() %>% 
  rownames_to_column("attribute") %>% 
  mutate(att.label = c("hard 200-3000m", "soft 30-100m", "eelgrass"))

# plot
ggplot(rov_df, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = region,
                 shape = region),
             size = 3, alpha = 0.8) +
  geom_segment(data = rov_envfit_coords, 
               aes(x = 0, xend = NMDS1,
                   y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.15, "cm")),
               col = "black") +
  geom_text(data = rov_envfit_coords, aes(label = att.label), size = 3) +
  scale_x_continuous(limits = c(-0.45, 0.45)) +
  scale_y_continuous(limits = c(-0.45, 0.45)) +
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +
  labs(title = "ROV",
       color = "",
       shape = "") + 
  theme_classic()
```
