---
title: "monitoring_site_locations"
author: "Joshua G. Smith"
date: '2022-07-21'
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(purrr)
library(sf)
library(tmap)
library(RColorBrewer)
```

## Read data

```{r paths}

# Define the paths and file names

#monitoring sites
path_aurora <- "/home/shares/ca-mpa/data/sync-data/monitoring"
sites_file <- "/site_locations.rda"
load(file.path(path_aurora, sites_file))

sf_locations <- st_as_sf(site_locations, coords = c("lon","lat"), crs = 4326) #make into sf object

#load GIS data
gis_dir <- "/home/shares/ca-mpa/data/sync-data/gis_data/processed"
state_water_poly <- readRDS(file.path(gis_dir, "CA_state_waters_polygons.Rds"))
state_waters_line <- readRDS(file.path(gis_dir, "CA_state_waters_polyline.Rds"))
mpas_orig <- readRDS(file.path(gis_dir, "CA_MPA_polygons.Rds"))




data.sf <- st_transform(x = location.data, crs=4326) #transform to WGS84



# Read California border
ca <- st_read(shp_ca)
# st_crs(ca)

```

#Take a look

```{r}
# Plot data
################################################################################

# MPA regions
# CA/OR, Alder Creek, Pigeon Point, Point Conception, CA/MEX 
region_lats <- c(39.0, 37.18, 34.5)

# Region labels
region_labels <- tibble(long_dd=c(-123.9, -122.9, -121, -118, -119.5),
                        lat_dd=c(40.5, 38.7, 36, 34.1, 34.8),
                        label=c("North\n(Dec 2012)", "North Central\n(May 2010)", "Central\n(Sep 2007)", "South\n(Jan 2012)", "N. Channel\nIslands (2003)"))

# Theme
my_theme <-  theme(axis.text=element_text(size=6),
                   axis.text.y = element_text(angle = 90, hjust = 0.5),
                   axis.title=element_blank(),
                   legend.text=element_text(size=6),
                   legend.title=element_text(size=8),
                   # Gridlines
                   panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(), 
                   axis.line = element_line(colour = "black"),
                   # Legend
                   legend.position = c(0.8, 0.7), # when color/size legends
                   # legend.position = c(0.8, 0.8), # when only color legend
                   legend.key.size = unit(0.4, "cm"),
                   legend.key = element_rect(fill=alpha('blue', 0)),
                   legend.background = element_rect(fill=alpha('blue', 0)))


# Plot data
(g <- ggplot() +
  # Plot regions
  geom_hline(mapping=aes(yintercept=region_lats)) +
  # Plot MPAs
   #geom_sf(data=site_locations) +
  geom_sf(data=sf_locations, aes(color=mpa_designation), 
             pch=21, stroke=0.1) + # size=2.5
  # Plot state waters
  geom_sf(data=state_waters_line, color="grey40", lwd=0.1) +
  # Plot region labels
  geom_text(data=region_labels, mapping=aes(x=long_dd, y=lat_dd, label=label), hjust=0, size=2.3) +
  # Labels
  labs(x="", y="") +
  # Legend
  scale_fill_manual(name="Designation", values=type_colors) +
  scale_size_continuous(name="Area (sqkm)") +
  guides(fill = guide_legend(order=1), size = guide_legend(order=2)) +
  # Axes
  scale_y_continuous(breaks=32:42) +
  # Crop
  coord_sf(xlim = c(-124.5, -117), ylim = c(32.5, 42)) +
  # Theme
  theme_bw() + my_theme
)

# Export figure
#ggsave(g, filename=file.path(plotdir, "Fig1_map_figure.png"), 
#       width=3.5, height=5.25, units="in", dpi=600)





```




